import { FormData } from './types';

export const INITIAL_FORM_DATA: FormData = {
  hazardType: 'Maila Tropical Cyclone',
  impactDates: '',
  province: 'Western Province',
  wardCommunity: '',
  assessmentDate: new Date().toISOString().split('T')[0],
  schoolName: '',
  siemisRegistration: '',
  gpsLocation: '',
  locationType: '',
  learningCentreType: '',
  educationProvider: '',
  accessibility: '',

  enrolment: {
    'ECE': createEmptyEnrolment(),
    'PPY': createEmptyEnrolment(),
    'Year 1': createEmptyEnrolment(),
    'Year 2': createEmptyEnrolment(),
    'Year 3': createEmptyEnrolment(),
    'Year 4': createEmptyEnrolment(),
    'Year 5': createEmptyEnrolment(),
    'Year 6': createEmptyEnrolment(),
    'Year 7': createEmptyEnrolment(),
    'Year 8': createEmptyEnrolment(),
    'Year 9': createEmptyEnrolment(),
    'Year 10': createEmptyEnrolment(),
    'Year 11': createEmptyEnrolment(),
    'Year 12': createEmptyEnrolment(),
    'Year 13': createEmptyEnrolment(),
  },
  staff: {
    teachers: createEmptyStaff(),
    otherStaff: createEmptyStaff(),
  },

  operationalStatus: 'Operational',
  closureDate: '',
  closureReason: '',
  reopeningDate: '',
  interimArrangements: [],

  overallDamageLevel: 0,
  facilityDamage: {
    'Classrooms': createEmptyFacilityDamage(),
    'Administration Block': createEmptyFacilityDamage(),
    'Library': createEmptyFacilityDamage(),
    'Laboratories': createEmptyFacilityDamage(),
    'WASH Facilities': createEmptyFacilityDamage(),
    'Water Supply': createEmptyFacilityDamage(),
    'Staff Housing': createEmptyFacilityDamage(),
    'Dormitories': createEmptyFacilityDamage(),
  },
  safeForUse: 'Pending Assessment',
  cordonedOff: 'No',
  immediateRisks: '',

  unusableClassrooms: 0,
  disruptedDays: 0,
  examsAffected: 'No',
  materialsAffected: 'No',
  materialLosses: [],
  impactDescription: '',

  studentsAffected: 0,
  displacedStudents: 0,
  disabilitiesAffected: 'No',
  disabilityDetails: [],
  boardingAffected: 'No',
  observedRisks: [],
  studentComments: '',

  teachersAffected: 0,
  teacherAccommodationDamaged: 'No',
  teachersDisplaced: 'No',
  substituteRequired: 'No',
  substituteNumber: 0,
  teacherImpactDetails: '',

  priorityNeedsImmediate: [],
  leadResponsibilityImmediate: [],
  priorityNeedsDetails: '',
  priorityNeedsShortTerm: [],
  leadResponsibilityShortTerm: [],
  priorityNeedsShortTermDetails: '',

  resourceRequirements: [
    { item: 'Temporary classrooms', quantity: '', cost: '', priority: 'Medium' },
    { item: 'Repair materials', quantity: '', cost: '', priority: 'Medium' },
    { item: 'Furniture', quantity: '', cost: '', priority: 'Medium' },
    { item: 'Learning materials', quantity: '', cost: '', priority: 'Medium' },
  ],

  attachments: [],
  photos: [],
  recommendations: '',

  assessor: { name: '', position: '', email: '', phone: '', date: '' },
  interviewee: { name: '', position: '', email: '', phone: '', date: '' },
};

function createEmptyEnrolment() {
  return {
    '3-4': { m: 0, f: 0 },
    '5': { m: 0, f: 0 },
    '6-11': { m: 0, f: 0 },
    '12-18': { m: 0, f: 0 },
    '19+': { m: 0, f: 0 },
    total: { m: 0, f: 0 },
  };
}

function createEmptyStaff() {
  return {
    '19-29': { m: 0, f: 0 },
    '30-39': { m: 0, f: 0 },
    '40-49': { m: 0, f: 0 },
    '50-59': { m: 0, f: 0 },
    '60+': { m: 0, f: 0 },
    total: { m: 0, f: 0 },
  };
}

function createEmptyFacilityDamage() {
  return {
    noDamage: 0,
    minor: 0,
    moderate: 0,
    significant: 0,
    completelyDestroyed: 0,
    photos: []
  };
}

export const SCHOOL_DIRECTORY = [
  { name: "Emmanuel ECE", ward: "Gizo", ep: "Destiny EP", type: "ECE", siemis: "78250" },
  { name: "St Marcellin ECE", ward: "North Kolombangara", ep: "Dioces of Gizo", type: "ECE", siemis: "75860" },
  { name: "St. Peter's ECE (Gizo)", ward: "Gizo", ep: "Dioces of Gizo", type: "ECE", siemis: "73060" },
  { name: "United Church Gizo ECE", ward: "Gizo", ep: "United Church EP", type: "ECE", siemis: "73610" },
  { name: "Babanga ECE", ward: "Gizo", ep: "Western Province EP", type: "ECE", siemis: "78330" },
  { name: "Gizo ECE", ward: "Gizo", ep: "Western Province EP", type: "ECE", siemis: "77160" },
  { name: "Ngari ECE", ward: "Gizo", ep: "Western Province EP", type: "ECE", siemis: "71010" },
  { name: "Poitete ECE", ward: "South Kolombangara", ep: "Western Province EP", type: "ECE", siemis: "71060" },
  { name: "Ringi ECE", ward: "South Kolombangara", ep: "Western Province EP", type: "ECE", siemis: "70970" },
  { name: "St Luke ECE", ward: "Gizo", ep: "Western Province EP", type: "ECE", siemis: "73070" },
  { name: "Emmanuel Christian Academy Primary", ward: "Gizo", ep: "Destiny EP", type: "Primary", siemis: "24550" },
  { name: "St Marcellin Primary", ward: "North Kolombangara", ep: "Diocese of Gizo EP", type: "Primary", siemis: "23880" },
  { name: "St John Bosco Nusabaruku Primary", ward: "Gizo", ep: "Diocese of Gizo EP", type: "Primary", siemis: "90517" },
  { name: "Ghatere Primary", ward: "North Kolombangara", ep: "SDA EP", type: "Primary", siemis: "13710" },
  { name: "Iriri Primary", ward: "North Kolombangara", ep: "SDA EP", type: "Primary", siemis: "10540" },
  { name: "Jack Harbour Primary", ward: "South Kolombangara", ep: "SDA EP", type: "Primary", siemis: "21120" },
  { name: "Kaza Primary", ward: "South Kolombangara", ep: "SDA EP", type: "Primary", siemis: "10490" },
  { name: "Mendina Primary", ward: "North Kolombangara", ep: "SDA EP", type: "Primary", siemis: "13760" },
  { name: "Tuki/Lodumoe Primary", ward: "North Kolombangara", ep: "SDA EP", type: "Primary", siemis: "13830" },
  { name: "Varu Adventist Primary", ward: "South Kolombangara", ep: "SDA EP", type: "Primary", siemis: "23190" },
  { name: "Vavanga Primary", ward: "North Kolombangara", ep: "SDA EP", type: "Primary", siemis: "21550" },
  { name: "Alpheus Rore Memorial Primary", ward: "Gizo", ep: "SDA EP", type: "Primary", siemis: "90536" },
  { name: "Ngari Primary", ward: "Gizo", ep: "United Church EP", type: "Primary", siemis: "24340" },
  { name: "Babanga Primary", ward: "Gizo", ep: "Western Province EP", type: "Primary", siemis: "24630" },
  { name: "Vao Sausepe Primary", ward: "North Kolombangara", ep: "Western Province EP", type: "Primary", siemis: "24680" },
  { name: "Ngari Secondary", ward: "Gizo", ep: "Western Province EP", type: "SS", siemis: "11280" },
  { name: "Patupaele Secondary", ward: "North Kolombangara", ep: "Western Province EP", type: "SS", siemis: "90538" },
  { name: "Titiana CHS - Secondary", ward: "Gizo", ep: "United Church EP", type: "CHS", siemis: "10180" },
  { name: "Titiana CHS - Primary", ward: "Gizo", ep: "United Church EP", type: "CHS", siemis: "10180" },
  { name: "Gizo CHS - Secondary", ward: "Gizo", ep: "Western Province EP", type: "CHS", siemis: "11490" },
  { name: "Gizo CHS - Primary", ward: "Gizo", ep: "Western Province EP", type: "CHS", siemis: "11490" },
  { name: "Kaza CHS - Secondry", ward: "South Kolombangara", ep: "Western Province EP", type: "CHS", siemis: "24380" },
  { name: "Poitete CHS - Secondary", ward: "South Kolombangara", ep: "Western Province EP", type: "CHS", siemis: "14620" },
  { name: "Poitete CHS - Primary", ward: "South Kolombangara", ep: "Western Province EP", type: "CHS", siemis: "14620" },
  { name: "Ringi Cove CHS - Secondary", ward: "South Kolombangara", ep: "Western Province EP", type: "CHS", siemis: "11610" },
  { name: "Ringi Cove CHS - Primary", ward: "South Kolombangara", ep: "Western Province EP", type: "CHS", siemis: "11610" },
  { name: "Kukudu NSS", ward: "North Kolombangara", ep: "SDA EP", type: "NSS", siemis: "20200" },
  { name: "Kukudu Primary", ward: "North Kolombangara", ep: "SDA EP", type: "Primary", siemis: "10550" },
  { name: "Holy Rosary Nila ECE", ward: "Inner Shortlands", ep: "Diocese of Gizo EP", type: "ECE", siemis: "71730" },
  { name: "Pirumeri ECE", ward: "Inner Shortlands", ep: "Western Province EP", type: "ECE", siemis: "71600" },
  { name: "Harapa ECE", ward: "Inner Shortlands", ep: "Western Province EP", type: "ECE", siemis: "71620" },
  { name: "Kariki ECE", ward: "Outer Shortlands", ep: "United Church EP", type: "ECE", siemis: "77200" },
  { name: "Aleang ECE", ward: "Outer Shortlands", ep: "Western Province EP", type: "ECE", siemis: "71640" },
  { name: "Gaomae ECE", ward: "Outer Shortlands", ep: "Western Province EP", type: "ECE", siemis: "71720" },
  { name: "Komaleai ECE", ward: "Inner Shortlands", ep: "Western Province EP", type: "ECE", siemis: "71610" },
  { name: "Nuhu ECE", ward: "Inner Shortlands", ep: "Western Province EP", type: "ECE", siemis: "77560" },
  { name: "Sacred Heart Maleai ECE", ward: "Inner Shortlands", ep: "Western Province EP", type: "ECE", siemis: "71800" },
  { name: "Samanago ECE", ward: "Outer Shortlands", ep: "Western Province EP", type: "ECE", siemis: "71580" },
  { name: "Toumoa ECE", ward: "Outer Shortlands", ep: "Western Province EP", type: "ECE", siemis: "71630" },
  { name: "St John Bosco Nila Primary", ward: "Inner Shortlands", ep: "Diocese of Gizo EP", type: "Primary", siemis: "11020" },
  { name: "Falamae Primary", ward: "Outer Shortlands", ep: "United Church EP", type: "Primary", siemis: "11570" },
  { name: "Kariki Primary", ward: "Outer Shortlands", ep: "United Church EP", type: "Primary", siemis: "10730" },
  { name: "Aleang Primary", ward: "Outer Shortlands", ep: "Western Province EP", type: "Primary", siemis: "14940" },
  { name: "Gaomai Primary", ward: "Outer Shortlands", ep: "Western Province EP", type: "Primary", siemis: "13050" },
  { name: "Harapa Primary", ward: "Inner Shortlands", ep: "Western Province EP", type: "Primary", siemis: "12960" },
  { name: "Komaleai Primary", ward: "Inner Shortlands", ep: "Western Province EP", type: "Primary", siemis: "15080" },
  { name: "Koliai Primary", ward: "Inner Shortlands", ep: "Western Province EP", type: "Primary", siemis: "21460" },
  { name: "Maleai Primary", ward: "Inner Shortlands", ep: "Western Province EP", type: "Primary", siemis: "11190" },
  { name: "Nuhu Primary", ward: "Inner Shortlands", ep: "Western Province EP", type: "Primary", siemis: "14090" },
  { name: "Pirumeri Primary", ward: "Inner Shortlands", ep: "Western Province EP", type: "Primary", siemis: "21470" },
  { name: "Samanago Primary", ward: "Outer Shortlands", ep: "Western Province EP", type: "Primary", siemis: "23770" },
  { name: "Toumoa Primary", ward: "Outer Shortlands", ep: "Western Province EP", type: "Primary", siemis: "12770" },
  { name: "St John Bosco Senior Secondary", ward: "Inner Shortlands", ep: "Diocese of Gizo EP", type: "SS", siemis: "24690" },
  { name: "St John Bosco Tuha CHS", ward: "Inner Shortlands", ep: "Diocese of Gizo EP", type: "CHS", siemis: "21440" },
  { name: "Eleoteve ECE", ward: "Mbilua", ep: "United Church EP", type: "ECE", siemis: "77150" },
  { name: "Parasau ECE", ward: "Irringilla", ep: "Western Province EP", type: "ECE", siemis: "74420" },
  { name: "Supato ECE", ward: "Vonunu", ep: "United Church EP", type: "ECE", siemis: "74520" },
  { name: "Shalom Primary", ward: "Vonunu", ep: "Destiny EP", type: "Primary", siemis: "24960" },
  { name: "JAC Primary", ward: "Dovele", ep: "SDA EP", type: "Primary", siemis: "24120" },
  { name: "Vare Tutty Primary", ward: "Dovele", ep: "SDA EP", type: "Primary", siemis: "10600" },
  { name: "Karokesa Primary", ward: "Dovele", ep: "United Church EP", type: "Primary", siemis: "11160" },
  { name: "Kolokolo Primary", ward: "Mbilua", ep: "United Church EP", type: "Primary", siemis: "11080" },
  { name: "Lambulambu Primary", ward: "Mbilua", ep: "United Church EP", type: "Primary", siemis: "11270" },
  { name: "Maravari Primary", ward: "Mbilua", ep: "United Church EP", type: "Primary", siemis: "11200" },
  { name: "Sambora Primary", ward: "Vonunu", ep: "United Church EP", type: "Primary", siemis: "22210" },
  { name: "Sibilado Primary", ward: "Dovele", ep: "United Church EP", type: "Primary", siemis: "11470" },
  { name: "Supato Primary", ward: "Vonunu", ep: "United Church EP", type: "Primary", siemis: "13400" },
  { name: "Valapata Primary", ward: "Mbilua", ep: "United Church EP", type: "Primary", siemis: "14580" },
  { name: "Vatoro Extension", ward: "Irringilla", ep: "United Church EP", type: "Primary", siemis: "21540" },
  { name: "Rumavatu Primary", ward: "Irringilla", ep: "United Church EP", type: "Primary", siemis: "90519" },
  { name: "Beiporo Primary", ward: "Vonunu", ep: "United Church EP", type: "Primary", siemis: "90532" },
  { name: "Malosova Primary", ward: "Vonunu", ep: "Western Province EP", type: "Primary", siemis: "25000" },
  { name: "Parasau Primary", ward: "Irringilla", ep: "Western Province EP", type: "Primary", siemis: "90453" },
  { name: "Roqesama Primary", ward: "Vonunu", ep: "Western Province EP", type: "Primary", siemis: "25010" },
  { name: "Bilua CHS - Secondary", ward: "Mbilua", ep: "United Church EP", type: "CHS", siemis: "21490" },
  { name: "Bilua CHS - Primary", ward: "Mbilua", ep: "United Church EP", type: "CHS", siemis: "21490" },
  { name: "Eleoteve CHS - Secondary", ward: "Mbilua", ep: "United Church EP", type: "CHS", siemis: "15480" },
  { name: "Eleoteve CHS - Primary", ward: "Mbilua", ep: "United Church EP", type: "CHS", siemis: "15480" },
  { name: "Iriqila CHS - Secondary", ward: "Irringilla", ep: "United Church EP", type: "CHS", siemis: "11620" },
  { name: "Iriqila CHS - Primary", ward: "Irringilla", ep: "United Church EP", type: "CHS", siemis: "11620" },
  { name: "Leona CHS - Secondary", ward: "Irringilla", ep: "United Church EP", type: "CHS", siemis: "11260" },
  { name: "Leona CHS - Primary", ward: "Irringilla", ep: "United Church EP", type: "CHS", siemis: "11260" },
  { name: "Sibila CHS - Secondary", ward: "Dovele", ep: "United Church EP", type: "CHS", siemis: "11540" },
  { name: "Sibila CHS - Primary", ward: "Dovele", ep: "United Church EP", type: "CHS", siemis: "11540" },
  { name: "Varese CHS - Secondary", ward: "Vonunu", ep: "United Church EP", type: "CHS", siemis: "11600" },
  { name: "Varese CHS - Primary", ward: "Vonunu", ep: "United Church EP", type: "CHS", siemis: "11600" },
  { name: "Reginald Chapman Nicholson College", ward: "Vonunu", ep: "United Church EP", type: "TVET", siemis: "20160" },
  { name: "Jones Adventist College CHS", ward: "Dovele", ep: "SDA EP", type: "CHS", siemis: "21570" },
  { name: "Keara ECE", ward: "South Rannoga", ep: "United Church EP", type: "ECE", siemis: "77220" },
  { name: "Obobulu ECE", ward: "South Rannoga", ep: "United Church EP", type: "ECE", siemis: "75130" },
  { name: "Pienuna ECE", ward: "South Rannoga", ep: "United Church EP", type: "ECE", siemis: "75610" },
  { name: "Koriovuku ECE", ward: "Central Ranongga", ep: "Western Province EP", type: "ECE", siemis: "74460" },
  { name: "Buri Primary", ward: "North Ranongga", ep: "SDA EP", type: "Primary", siemis: "24360" },
  { name: "Mondo Primary", ward: "North Ranongga", ep: "SDA EP", type: "Primary", siemis: "13850" },
  { name: "Patuboliboli Primary", ward: "Central Ranongga", ep: "SDA EP", type: "Primary", siemis: "13930" },
  { name: "Tavutavu Primary", ward: "North Ranongga", ep: "SDA EP", type: "Primary", siemis: "90520" },
  { name: "Kalaro Primary", ward: "Simbo", ep: "United Church EP", type: "Primary", siemis: "10060" },
  { name: "Keara Primary", ward: "South Rannoga", ep: "United Church EP", type: "Primary", siemis: "11130" },
  { name: "Kolomali Primary", ward: "Central Ranongga", ep: "United Church EP", type: "Primary", siemis: "15510" },
  { name: "Kongu Primary", ward: "South Rannoga", ep: "United Church EP", type: "Primary", siemis: "15130" },
  { name: "Koriovuku Primary", ward: "Central Ranongga", ep: "United Church EP", type: "Primary", siemis: "11390" },
  { name: "Kundu Primary", ward: "North Ranongga", ep: "United Church EP", type: "Primary", siemis: "11290" },
  { name: "Obobulu Primary", ward: "South Rannoga", ep: "United Church EP", type: "Primary", siemis: "11380" },
  { name: "Suava Primary", ward: "South Rannoga", ep: "United Church EP", type: "Primary", siemis: "14630" },
  { name: "Nusa Simbo Primary", ward: "Simbo", ep: "United Church EP", type: "Primary", siemis: "90521" },
  { name: "Lengana CHS - Secondary", ward: "Simbo", ep: "United Church EP", type: "CHS", siemis: "11930" },
  { name: "Lengana CHS - Primary", ward: "Simbo", ep: "United Church EP", type: "CHS", siemis: "11930" },
  { name: "Pienuna CHS - Secondary", ward: "South Rannoga", ep: "United Church EP", type: "CHS", siemis: "11150" },
  { name: "Pienuna CHS - Primary", ward: "South Rannoga", ep: "United Church EP", type: "CHS", siemis: "11150" },
  { name: "Sidoko CHS - Secondary", ward: "South Rannoga", ep: "United Church EP", type: "CHS", siemis: "11530" },
  { name: "Pange Primary", ward: "South Rannoga", ep: "United Church EP", type: "Primary", siemis: "90518" },
  { name: "Sidoko CHS - Primary", ward: "South Rannoga", ep: "United Church EP", type: "CHS", siemis: "11530" },
  { name: "Buri CHS - Secondary", ward: "North Ranongga", ep: "Western Province EP", type: "CHS", siemis: "13820" },
  { name: "Bareho ECE", ward: "Nono", ep: "SDA EP", type: "ECE", siemis: "78870" },
  { name: "Tetemara ECE", ward: "North Vangunu", ep: "SDA EP", type: "ECE", siemis: "78120" },
  { name: "Chubikopi ECE", ward: "Nggatokae", ep: "United Church EP", type: "ECE", siemis: "71470" },
  { name: "Michi ECE", ward: "North Vangunu", ep: "United Church EP", type: "ECE", siemis: "77290" },
  { name: "Patukae ECE", ward: "North Vangunu", ep: "United Church EP", type: "ECE", siemis: "77590" },
  { name: "Patutiva ECE", ward: "Buinitusu", ep: "United Church EP", type: "ECE", siemis: "74480" },
  { name: "Seghe ECE", ward: "North Vangunu", ep: "United Church EP", type: "ECE", siemis: "77620" },
  { name: "Biche ECE", ward: "Nggatokae", ep: "Western Province EP", type: "ECE", siemis: "76120" },
  { name: "Kavolavata ECE", ward: "Nggatokae", ep: "Western Province EP", type: "ECE", siemis: "75120" },
  { name: "Merusu ECE", ward: "Nggatokae", ep: "Western Province EP", type: "ECE", siemis: "75110" },
  { name: "Bareho Primary", ward: "Nono", ep: "SDA EP", type: "Primary", siemis: "13770" },
  { name: "Batuna Primary", ward: "Nggatokae", ep: "SDA EP", type: "Primary", siemis: "10590" },
  { name: "Bili Primary", ward: "Nggatokae", ep: "SDA EP", type: "Primary", siemis: "13790" },
  { name: "Buinitusu Primary", ward: "North Vangunu", ep: "SDA EP", type: "Primary", siemis: "13810" },
  { name: "Hinakole Primary", ward: "Nggatokae", ep: "SDA EP", type: "Primary", siemis: "13920" },
  { name: "Kokete Primary", ward: "Nggatokae", ep: "SDA EP", type: "Primary", siemis: "10610" },
  { name: "Peava Primary", ward: "Nggatokae", ep: "SDA EP", type: "Primary", siemis: "13940" },
  { name: "Penjuku Primary", ward: "North Vangunu", ep: "SDA EP", type: "Primary", siemis: "13900" },
  { name: "Sobiro Primary", ward: "Nggatokae", ep: "SDA EP", type: "Primary", siemis: "22560" },
  { name: "Telina Primary", ward: "North Vangunu", ep: "SDA EP", type: "Primary", siemis: "13960" },
  { name: "Tetemara Primary", ward: "North Vangunu", ep: "SDA EP", type: "Primary", siemis: "13870" },
  { name: "Tombe SDA Primary", ward: "Nono", ep: "SDA EP", type: "Primary", siemis: "24670" },
  { name: "Ulona Primary", ward: "North Vangunu", ep: "SDA EP", type: "Primary", siemis: "13840" },
  { name: "Chubikopi Primary", ward: "Nggatokae", ep: "United Church EP", type: "Primary", siemis: "14560" },
  { name: "Chuchulu Primary", ward: "Buinitusu", ep: "United Church EP", type: "Primary", siemis: "22160" },
  { name: "Michi Primary", ward: "North Vangunu", ep: "United Church EP", type: "Primary", siemis: "15300" },
  { name: "Nazareth Primary", ward: "North Vangunu", ep: "United Church EP", type: "Primary", siemis: "15270" },
  { name: "Seghe Primary", ward: "North Vangunu", ep: "United Church EP", type: "Primary", siemis: "11640" },
  { name: "Vakambo Primary", ward: "Buinitusu", ep: "United Church EP", type: "Primary", siemis: "13260" },
  { name: "Zaira Primary", ward: "Buinitusu", ep: "United Church EP", type: "Primary", siemis: "22550" },
  { name: "Biche Primary", ward: "Nggatokae", ep: "Western Province EP", type: "Primary", siemis: "23760" },
  { name: "Kavolavata Primary", ward: "Nggatokae", ep: "Western Province EP", type: "Primary", siemis: "21530" },
  { name: "Merusu Primary", ward: "Nggatokae", ep: "Western Province EP", type: "Primary", siemis: "21590" },
  { name: "Niniveh Primary", ward: "Nono", ep: "Western Province EP", type: "Primary", siemis: "25110" },
  { name: "SR Academy Secondary", ward: "Buinitusu", ep: "SR EP", type: "SS", siemis: "90534" },
  { name: "Bekabeka CHS - Secondary", ward: "Nggatokae", ep: "SDA EP", type: "CHS", siemis: "13780" },
  { name: "Halisi CHS - Secondary", ward: "North Vangunu", ep: "United Church EP", type: "CHS", siemis: "11510" },
  { name: "Halisi CHS - Primary", ward: "North Vangunu", ep: "United Church EP", type: "CHS", siemis: "11510" },
  { name: "Patukae CHS - Secondary", ward: "North Vangunu", ep: "United Church EP", type: "CHS", siemis: "11120" },
  { name: "Patukae CHS - Primary", ward: "North Vangunu", ep: "United Church EP", type: "CHS", siemis: "11120" },
  { name: "Patutiva CHS - Secondary", ward: "Buinitusu", ep: "United Church EP", type: "CHS", siemis: "14600" },
  { name: "Patutiva CHS - Primary", ward: "Buinitusu", ep: "United Church EP", type: "CHS", siemis: "14600" },
  { name: "Viru CHS - Secondry", ward: "Nono", ep: "Western Province EP", type: "CHS", siemis: "90430" },
  { name: "Paradise ECE", ward: "Kusaghe", ep: "Western Province EP", type: "ECE", siemis: "78020" },
  { name: "Jella Primary", ward: "Kolombaghea", ep: "SDA EP", type: "Primary", siemis: "13980" },
  { name: "Mase Primary", ward: "Kusaghe", ep: "SDA EP", type: "Primary", siemis: "21080" },
  { name: "Ramata Primary", ward: "Kusaghe", ep: "SDA EP", type: "Primary", siemis: "21810" },
  { name: "Baini Adventist Primary", ward: "Kolombaghea", ep: "Western Province EP", type: "Primary", siemis: "90589" },
  { name: "Hovoro Primary", ward: "Kolombaghea", ep: "Western Province EP", type: "Primary", siemis: "10530" },
  { name: "Paradise CHS - Secondary", ward: "Kusaghe", ep: "Western Province EP", type: "CHS", siemis: "14160" },
  { name: "Paradise CHS - Primary", ward: "Kusaghe", ep: "Western Province EP", type: "CHS", siemis: "14160" },
  { name: "Dekurana Integrated Secondary School", ward: "Kolombaghea", ep: "Western Province EP", type: "SS", siemis: "25170" },
  { name: "Gerasi CHS", ward: "Kolombaghea", ep: "Western Province EP", type: "CHS", siemis: "90120" },
  { name: "Kongukolo CHS", ward: "Kolombaghea", ep: "Western Province EP", type: "CHS", siemis: "24370" },
  { name: "Lokuru Primary", ward: "South Rendova", ep: "SDA EP", type: "Primary", siemis: "13750" },
  { name: "Tirongo SDA Primary", ward: "South Rendova", ep: "SDA EP", type: "Primary", siemis: "90535" },
  { name: "Agagana Primary", ward: "South Rendova", ep: "United Church EP", type: "Primary", siemis: "13300" },
  { name: "Ha'apai Primary", ward: "Roviana Lagoon", ep: "United Church EP", type: "Primary", siemis: "15460" },
  { name: "Brondie Primary", ward: "North Rendova", ep: "AGAWA EP", type: "Primary" },
  { name: "Baguri Primary", ward: "Roviana Lagoon", ep: "United Church EP", type: "Primary", siemis: "90553" },
  { name: "Madali Primary", ward: "North Rendova", ep: "Western Province EP", type: "Primary", siemis: "24580" },
  { name: "Buruku CHS - Secondary", ward: "South Rendova", ep: "SDA EP", type: "CHS", siemis: "10580" },
  { name: "Buruku CHS - Primary", ward: "South Rendova", ep: "SDA EP", type: "CHS", siemis: "10580" },
  { name: "Vancouver CHS - Secondary", ward: "South Rendova", ep: "United Church EP", type: "CHS", siemis: "10740" },
  { name: "Vancouver CHS - Primary", ward: "South Rendova", ep: "United Church EP", type: "CHS", siemis: "10740" },
  { name: "Saint Eusebius ECE", ward: "Noro", ep: "Diocese of Gizo EP", type: "ECE", siemis: "71560" },
  { name: "Baeroko ECE", ward: "Munda", ep: "United Church EP", type: "ECE", siemis: "77050" },
  { name: "Dunde ECE", ward: "Nusa Roviana", ep: "United Church EP", type: "ECE", siemis: "71690" },
  { name: "Kokeqolo ECE", ward: "Munda", ep: "United Church EP", type: "ECE", siemis: "77090" },
  { name: "Rarumana ECE", ward: "Vonavona", ep: "United Church EP", type: "ECE", siemis: "73050" },
  { name: "Arara ECE", ward: "Nusa Roviana", ep: "Western Province EP", type: "ECE", siemis: "77130" },
  { name: "Niumala ECE", ward: "Vonavona", ep: "Western Province EP", type: "ECE", siemis: "71030" },
  { name: "Noro ECE", ward: "Noro", ep: "United Church EP", type: "ECE", siemis: "71550" },
  { name: "Kinamara Primary", ward: "Vonavona", ep: "United Church EP", type: "Primary", siemis: "23220" },
  { name: "Tehila Primary", ward: "Noro", ep: "Destiny EP", type: "Primary", siemis: "25100" },
  { name: "Boboe Primary", ward: "Vonavona", ep: "SDA EP", type: "Primary", siemis: "21500" },
  { name: "Baeroko Primary", ward: "Munda", ep: "United Church EP", type: "Primary", siemis: "22250" },
  { name: "Banga Primary", ward: "Munda", ep: "United Church EP", type: "Primary", siemis: "10460" },
  { name: "Nusa Roviana Primary", ward: "Nusa Roviana", ep: "United Church EP", type: "Primary", siemis: "11360" },
  { name: "Arara Primary", ward: "Nusa Roviana", ep: "Western Province EP", type: "Primary", siemis: "15030" },
  { name: "Niu Mala Primary", ward: "Vonavona", ep: "Western Province EP", type: "Primary", siemis: "15520" },
  { name: "SDA Garden Primary", ward: "Noro", ep: "Western Province EP", type: "Primary", siemis: "24610" },
  { name: "Sychar Primary", ward: "Vonavona", ep: "Western Province EP", type: "Primary", siemis: "24350" },
  { name: "Tehila Secondary", ward: "Noro", ep: "Western Province EP", type: "SS", siemis: "90548" },
  { name: "Barasipo CHS - Secondary", ward: "Vonavona", ep: "United Church EP", type: "CHS", siemis: "10630" },
  { name: "Barasipo CHS - Primary", ward: "Vonavona", ep: "United Church EP", type: "CHS", siemis: "10630" },
  { name: "Dunde CHS - Secondary", ward: "Nusa Roviana", ep: "United Church EP", type: "CHS", siemis: "15250" },
  { name: "Dunde CHS - Primary", ward: "Nusa Roviana", ep: "United Church EP", type: "CHS", siemis: "15250" },
  { name: "Kokeqolo CHS - Secondary", ward: "Munda", ep: "United Church EP", type: "CHS", siemis: "11110" },
  { name: "Kokeqolo CHS - Primary", ward: "Munda", ep: "United Church EP", type: "CHS", siemis: "11110" },
  { name: "Rarumana CHS - Secondary", ward: "Vonavona", ep: "United Church EP", type: "CHS", siemis: "11580" },
  { name: "Rarumana CHS - Primary", ward: "Vonavona", ep: "United Church EP", type: "CHS", siemis: "11580" },
  { name: "Rawaki CHS - Secondary", ward: "Vonavona", ep: "United Church EP", type: "CHS", siemis: "14080" },
  { name: "Rawaki CHS - Primary", ward: "Vonavona", ep: "United Church EP", type: "CHS", siemis: "14080" },
  { name: "Noro CHS - Secondary", ward: "Munda", ep: "Western Province EP", type: "CHS", siemis: "10450" },
  { name: "Noro CHS - Primary", ward: "Munda", ep: "Western Province EP", type: "CHS", siemis: "10450" },
  { name: "Biulah PSS", ward: "Nusa Roviana", ep: "Western Province EP", type: "PSS", siemis: "20050" },
  { name: "Goldie College NSS", ward: "Munda", ep: "United Church EP", type: "NSS", siemis: "20180" },
];
